Remove Swift 5.0 and 5.1 support, and add CI config
apple/swift-nio-transport-services pull request #122
Opened 2021-06-22 17:51 UTC by Davidde94

NIOTS only had CI configs for Swift 5.0, so I've added a few more to bring our coverage up to match other members of the NIO family. Additionally update `Package.swift` to drop support for 5.0 and 5.1.

2021-06-22 17:52 UTC, Davidde94 commented
Hey @yim-lee this one is a bit more involved. Could you please:

- [ ] Delete the old 5.0 job
- [ ] Make new jobs for 5.2, 5.3, 5.4, and main

Johannes added main in a separate PR #114

2021-06-22 18:44 UTC, yim-lee commented
@swift-nio-bot test this please

2021-06-22 18:52 UTC, yim-lee commented
@Davidde94 CI changes done.

I added 5.2, 5.3, and 5.4 jobs to required list.

Unrelated to this, but I have created a [soundness job](https://ci.swiftserver.group/job/swift-nio-transport-services-soundness-prb/). It should be added to the required list as well but currently it's failing because we need to update `scripts/sanity.sh` and `docker-compose.yaml` first.

2021-06-22 20:40 UTC, Davidde94 commented
@yim-lee thanks a lot, I'll fix it now

2021-06-23 07:34 UTC, Lukasa commented on docker/docker-compose.1804.53.yaml
> +        ubuntu_version: "xenial"
```suggestion
        ubuntu_version: "bionic"
```

2021-06-23 07:34 UTC, Lukasa commented on docker/docker-compose.2004.54.yaml
> +    image: swift-nio-transport-services:18.04-5.4
```suggestion
    image: swift-nio-transport-services:20.04-5.4
```

2021-06-23 07:34 UTC, Lukasa commented on docker/docker-compose.2004.54.yaml
> +    image: swift-nio-transport-services:18.04-5.4
```suggestion
    image: swift-nio-transport-services:20.04-5.4
```

2021-06-23 07:34 UTC, Lukasa commented on docker/docker-compose.2004.54.yaml
> +    image: swift-nio-transport-services:18.04-5.4
```suggestion
    image: swift-nio-transport-services:20.04-5.4
```

2021-06-23 07:36 UTC, Lukasa requested changes
While we're here, I know it's not your fault @Davidde94 but the nightly dockerfile is just _nonsense_. Can you rewrite it to match the ones here instead of just being a copy from NIO?

2021-06-23 07:53 UTC, Davidde94 commented
Yep no problem

2021-06-23 07:56 UTC, Lukasa approved these changes
LGTM.

2021-06-23 07:57 UTC, merged