State Managed Listeners
apple/swift-nio-transport-services pull request #175
Opened 2023-05-21 12:22 UTC by Joannis

Extract the NWListener code into `StateManagedListenerChannel`

### Motivation:

When implementing #68, a lot of code ended up being identical between TCP and UDP. Like #174, this PR paves the way to adding UDP, with very little overhead code. It moves the code that is used to represent NWListener as a Channel into its own protocol, that can then be applied to both TCP and UDP implementations.

### Modifications:

- Added `StateManagedListenerChannel` that has all the logic for handling a NWConnection as a NIO.Channel.
- Made the AcceptHandler generic for use with both TCP and UDP

### Result:

This makes implementing UDP much simpler, and without redundant code.

### Notes

This PR works off #174 , and should therefore be viewed as a diff based on #174 to get a clean picture.

2023-07-08 11:42 UTC, Lukasa commented
@Joannis any chance you can rebase this on the new `main` for easier review?

2023-07-08 11:47 UTC, Joannis commented
Will do @Lukasa , doing so now

2023-07-08 11:54 UTC, Lukasa requested changes
Only a few nits here, otherwise we're good.

2023-07-08 11:54 UTC, Lukasa commented on Sources/NIOTransportServices/AcceptHandler.swift
> +import NIO
```suggestion
import NIOCore
```

2023-07-08 11:54 UTC, Lukasa commented on Sources/NIOTransportServices/UDPOptions+SocketChannelOption.swift
> +// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
```suggestion
// Copyright (c) 2023 Apple Inc. and the SwiftNIO project authors
```

2023-07-08 11:54 UTC, Lukasa commented on Sources/NIOTransportServices/AcceptHandler.swift
> +#if canImport(Network)
We need a license header in this file.

2023-07-08 11:54 UTC, Lukasa commented on Sources/NIOTransportServices/NIOTSListenerChannel.swift
> +            protocolOptions = .tcp(newValue)
We should add a defensive check that we already had tcp options here, at least a debug mode one.

2023-07-08 11:54 UTC, Lukasa commented on Sources/NIOTransportServices/NIOTSListenerChannel.swift
> +            childProtocolOptions = .tcp(newValue)
Same note about a defensive check here.

2023-07-08 11:54 UTC, Lukasa commented on Sources/NIOTransportServices/StateManagedListenerChannel.swift
> +#if canImport(Network)
We need a license header here.

2023-07-08 11:54 UTC, Lukasa commented on Sources/NIOTransportServices/StateManagedListenerChannel.swift
> +        fatalError("This function must be overridden by thes subclass")
```suggestion
        fatalError("This function must be overridden by the subclass")
```

2023-07-08 12:04 UTC, Joannis commented
@Lukasa ready for review again

2023-07-08 13:37 UTC, Lukasa commented on Sources/NIOTransportServices/NIOTSConnectionChannel.swift
> +    private func dropOutNIOTransportServicesTestsstandingWrites(error: Error) {
This looks wrong

2023-07-08 13:37 UTC, Lukasa commented on Sources/NIOTransportServices/UDPOptions+SocketChannelOption.swift
> +//===----------------------------------------------------------------------===//
This doc comment has some tools-version stuff in it that shouldn't be here.

2023-07-08 14:25 UTC, Joannis commented on Sources/NIOTransportServices/NIOTSConnectionChannel.swift
> +    private func dropOutNIOTransportServicesTestsstandingWrites(error: Error) {
Oops, missed that completely

2023-07-09 11:40 UTC, Lukasa approved these changes
Fantastic, let's land this as well.

2023-07-09 11:41 UTC, merged