Feature/jo/state managed udp
apple/swift-nio-transport-services pull request #176
Opened 2023-05-21 12:29 UTC by Joannis

Adds support for UDP clients and servers.

### Motivation:

This change was made because UDP support was lacking on iOS. It's needed by my DNS client implementation, which I am in turn using for an iOS app I'm working on relying on SRV typed records.

### Modifications:

- Adds a `NIOTSDatagramListenerBootstrap` for making UDP services
  - Adds a `NIOTSDatagramListenerChannel` that accepts UDP connections
- Adds a `NIOTSDatagramChannel` for UDP client connections
- Adds a `NIOTSDatagramBootstrap` that can create a new UDP client

### Notes

This PR relies on #174 and #175, but it separated so that it's easy to review.
This has been tested against my own libraries, but only features one test.

While I believe it to be working, I'm looking for feedback on how I can better test this implementation.

2023-07-08 13:33 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramBootstrap.swift
> +    /// may be constructed with an `EventLoopGroup` and by extenstion an `EventLoop`. As such an
```suggestion
    /// may be constructed with an `EventLoopGroup` and by extension an `EventLoop`. As such an
```

2023-07-08 13:33 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
> +import NIO
```suggestion
import NIOCore
```

2023-07-08 13:33 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
> +    internal var isActive0 = ManagedAtomic(false)
This can be `let`.

2023-07-08 13:33 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
> +    private var udpOptions: NWProtocolUDP.Options
This can be `let`.

2023-07-08 13:33 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramListenerChannel.swift
> +            protocolOptions = .udp(newValue)
We should check the original protocol options type.

2023-07-08 13:33 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramListenerChannel.swift
> +            childProtocolOptions = .udp(newValue)
We should check the original protocol options type.

2023-07-10 10:04 UTC, Joannis commented
@Lukasa updated

2023-07-10 10:04 UTC, Joannis commented
Note that there were 2 small issues in the state managed channels that I've had to fix as well

2023-07-20 10:05 UTC, Lukasa reviewed
Some initial comments.

2023-07-20 10:05 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramListener.swift
> +// Copyright (c) 2017-2021 Apple Inc. and the SwiftNIO project authors
```suggestion
// Copyright (c) 2017-2023 Apple Inc. and the SwiftNIO project authors
```

2023-07-20 10:05 UTC, Lukasa commented on Sources/NIOTransportServices/NIOTSConnectionChannel.swift
> +    private func dropOutNIOTransportServicesTestsstandingWrites(error: Error) {
Can you remove this change?

2023-08-09 13:23 UTC, Lukasa commented on Sources/NIOTransportServices/Datagram/NIOTSDatagramListener.swift
> +                                                         on: self.group.next() as! NIOTSEventLoop,
Is this use of `.next()` correct? We already called it above.

2023-08-10 12:38 UTC, Lukasa approved these changes

2023-08-10 12:38 UTC, Lukasa requested changes

2023-08-10 12:38 UTC, Lukasa commented on Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
> +#if canImport(Network)
This file is missing a license header.

2023-08-10 12:41 UTC, Joannis commented on Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
> +#if canImport(Network)
Done

2023-08-10 13:01 UTC, Lukasa approved these changes
Nice one, thanks.

2023-08-10 13:02 UTC, merged